# Generated by Django 5.0.6 on 2024-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tname",
                    models.CharField(max_length=100, verbose_name="Medicine name"),
                ),
                (
                    "cat",
                    models.IntegerField(
                        choices=[
                            (1, "drugs"),
                            (2, "supplement"),
                            (3, "medical_devices"),
                            (4, "personal_care"),
                            (5, "Nutrition"),
                        ],
                        verbose_name="Category",
                    ),
                ),
                (
                    "tprice",
                    models.CharField(max_length=50, verbose_name="Medicine price"),
                ),
                ("details", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("tiffin_image", models.ImageField(upload_to="image")),
            ],
        ),
    ]
