# Generated by Django 5.0.6 on 2024-05-29 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0002_meds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meds",
            old_name="tiffin_image",
            new_name="meds_image",
        ),
    ]
