# Generated by Django 5.0.6 on 2024-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0004_myorders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meds",
            name="cat",
            field=models.IntegerField(
                choices=[
                    (1, "Personal Care"),
                    (2, "Health Care Devices"),
                    (3, "Skin Care"),
                    (4, "Fitness Supplement"),
                    (5, "Ayurvedic Care"),
                    (6, "Health Care"),
                ],
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="meds",
            name="tname",
            field=models.CharField(max_length=100, verbose_name="Product name"),
        ),
        migrations.AlterField(
            model_name="meds",
            name="tprice",
            field=models.CharField(max_length=50, verbose_name="Product price"),
        ),
    ]
