# Generated by Django 5.0.6 on 2024-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0005_alter_meds_cat_alter_meds_tname_alter_meds_tprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="https://cdn-icons-png.flaticon.com/512/9187/9187604.png",
                upload_to="profile_photos",
            ),
        ),
    ]
