# Generated by Django 5.0.6 on 2024-05-30 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0006_alter_profile_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
