# Generated by Django 5.0.6 on 2024-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthapp", "0010_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cat",
            field=models.IntegerField(
                choices=[
                    (1, "Personal Care"),
                    (2, "Health Care Devices"),
                    (3, "Skin Care"),
                    (4, "Fitness Supplement"),
                    (5, "Ayurvedic Care"),
                    (6, "Health Care"),
                ],
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
